name: 'CI'

on:
  push: {}
  pull_request: {}
  workflow_call: {}

jobs:
  build:
    name: Build 🛠️
    uses: ./.github/workflows/run_build.yml
    secrets: inherit

  checks:
    name: Checks 📋
    uses: ./.github/workflows/run_checks.yml
    secrets: inherit

  tests:
    name: Test 🧪
    needs:
      - build
    uses: ./.github/workflows/run_tests.yml
    secrets: inherit
