name: "Release"

on:
  push:
    tags: []

jobs:
  build:
    name: Build 🛠️
    uses: ./.github/workflows/main.yml
  release:
    needs:
      - build
    name: Create Release 📢
    runs-on: ubuntu-latest
    steps:
      - name: Download tarball 📥
        uses: actions/download-artifact@v3
        with:
          name: tarball

      - name: Generate checksums 🔑
        run: |
          for x in *.tar.gz; do
            sha256sum $x > ${x}.sha256
          done

      - name: Attach to release 📦
        uses: softprops/action-gh-release@v1
        with:
          files: |
            nixos-wsl-x86_64-linux.tar.gz
            nixos-wsl-x86_64-linux.tar.gz.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
